from . import account_move
from . import account_move_line
from . import cleaning_request
from . import cleaning_team
from . import event_booking_line
from . import fleet_booking_line
from . import fleet_vehicle_model
from . import food_booking_line
from . import hotel_amenity
from . import hotel_floor
from . import hotel_room
from . import hotel_service
from . import maintenance_request
from . import maintenance_team
from . import room_booking
from . import room_booking_line
from . import service_booking_line
from . import id_details
from . import id_details_line
from . import restaurant
from . import kot_bot
from . import hotel_plan
from . import inherit_model

